# Generated by Django 5.2.4 on 2025-07-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '6. Cart '},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '1. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='lecturevideo',
            options={'verbose_name_plural': '5.Lecture Videos '},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': '2.Rating '},
        ),
        migrations.AlterModelOptions(
            name='student_enrollment',
            options={'verbose_name_plural': '7. Student Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '4.Topics '},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
