# Generated by Django 5.2.4 on 2025-07-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_cart_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
