# Generated by Django 5.2.4 on 2025-07-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('course', '0003_delete_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='Teacher.teacher'),
        ),
    ]
