# Generated by Django 5.2.4 on 2025-07-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_teacher_groups_and_more'),
        ('assignment', '0002_alter_assignment_teacher'),
        ('course', '0004_alter_course_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
